fix login if saml response is in body comment
dlenski/gp-saml-gui pull request #59
Opened 2022-09-30 18:16 UTC by ByteCommander

fixes https://github.com/dlenski/gp-saml-gui/issues/51

If there are no SAML and/or prelogin-cookie related related headers found in the server responses, this PR adds the functionality to check the response body for those values in embedded XML documents inside any HTML body comments.

2022-09-30 22:10 UTC, dlenski requested changes

2022-09-30 22:10 UTC, dlenski commented on gp_saml_gui.py
> +    def log_resource_text(self, resource, data, content_type, charset=None, show_headers=None):
Hmmm… I don't understand this removal.

In `log_resource_text`, you're changing `result`→`data`, and _removing_ `data = resource.get_data_finish(result)`; but in `response_callback`, you're _keeping_ `data = resource.get_data_finish(result)`.

It seems like either the parameter is `data`, or it's `result`, but it can't be both :)

2022-09-30 22:10 UTC, dlenski commented on gp_saml_gui.py
> +            self.check_done()
I seem to recall that there was an occasional race condition (details fuzzy :man_shrugging:) without the 1 second delay… any reason _not_ to keep it?

2022-09-30 22:10 UTC, dlenski commented on gp_saml_gui.py
> +                    print("[SAML   ] Response body comment does not seem to contain SAML tags, skipping")
Note that this will only be printed if the comment _causes XML parsing errors_, and not if the comment _simply doesn't contain any tags_ (e.g. `<!-- foo bar -->` won't lead us here).

2022-10-01 19:49 UTC, ByteCommander commented on gp_saml_gui.py
> +    def log_resource_text(self, resource, data, content_type, charset=None, show_headers=None):
Right, I tried first to remove the get_data_finish here completely and combine it with where I would have to call it to get the body for looking for SAML data, but seems like I forgot to revert that fully. 
Let me try and see if I get_data[_finish] can be possibly called twice or if it needs more refactoring (e.g. always loading the body unconditionally once first).

2022-10-01 19:54 UTC, ByteCommander commented on gp_saml_gui.py
> +            self.check_done()
It worked without it for me, and I could not understand the reasoning how the value of self.saml_result can possibly change between its assignment by the code above, and calling check_done. Seemed like an unnecessary slowdown of the whole workflow to me.
Also since we now branch off depending on whether the headers are already sufficient or whether we check the body too, it would need to be scheduled after either code path. 
Maybe we can have one call to check_done immediately after any saml_result assignment, and another one scheduled with delay just in case?

2022-10-01 19:56 UTC, ByteCommander commented on gp_saml_gui.py
> +                    print("[SAML   ] Response body comment does not seem to contain SAML tags, skipping")
Good catch, I forgot that then it would still become valid xml, due to having to add the `<fakexmlroot>` root tag around it. I'll change the message.

2022-10-01 21:40 UTC, ByteCommander commented on gp_saml_gui.py
> +            self.check_done()
I moved the recheck mechanism directly inside check_done() to always by default schedule itself once more later, after an unsuccessful check.

2022-10-07 12:53 UTC, rezekdan commented
tested this within our company and it works now

2022-11-17 17:03 UTC, ByteCommander commented
Any further updates or review comments on this, before it could get merged? @dlenski

2022-12-06 20:37 UTC, fang0654 commented
Just chiming in that one of the VPNs I've been using stopped working overnight, and it turns out this was the issue, and this PR fixed it!

2022-12-19 15:21 UTC, messiahUA commented
I hope this will be merged eventually.

2023-01-19 05:23 UTC, ghaith commented on gp_saml_gui.py
> +        print("Found comment: '%s'" % data)
I've been trying out the branch, and I think you need to add file=stderr to this print statement otherwise we cannot pass it to eval

2023-05-04 12:25 UTC, ByteCommander commented on gp_saml_gui.py
> +        print("Found comment: '%s'" % data)
Sorry for losing track of this PR. You're right, I did not notice that all logging was supposed to end up on stderr. This should be fixed now, thanks for the comment.

2023-05-04 19:58 UTC, dlenski commented
Thank you @ByteCommander for your patience and refinement here.

I tweaked the PR slightly (squash commits, cleanup), and tested it against [OpenConnect's `fake-gp-server.py`](https://gitlab.com/openconnect/openconnect/blob/master/tests/fake-gp-server.py) (which is the only GP SAML server tha I have access to right now :man_shrugging:)

1. In OpenConnect v9.10 directory:
```
$ cd openconnect/tests
$ ./fake-gp-server.py localhost 80000 certs/server-{cert,key}.pem &
```

2. Configure the fake server for SAML on the portal, with handoff to the gateway login, both using the `portal-userauthcookie`:
```
$ curl -k https://localhost:8000/CONFIGURE -d portal_saml=portal-userauthcookie -d portal_cookie=portal-userauthcookie
$ curl -k https://localhost:8000/CONFIGURE
Current configuration of fake GP server configuration:
TestConfiguration(gateways=('Default gateway',), portal_2fa=None, gw_2fa=None, portal_cookie='portal-userauthcookie', portal_saml='portal-userauthcookie', gateway_saml=None)
```

3. Use `gp-saml-gui localhost:8000` to do SAML authentication, verify that it works.

2023-05-04 20:02 UTC, merged