gp_saml_gui.py: ensure that proxies are disabled
dlenski/gp-saml-gui pull request #87
Opened 2024-01-05 10:24 UTC by mchehab

Using a proxy while trying to connect to VPN is problematic, as proxies are usually behind the VPN.

So, disable it when opening the WebKit window.

2024-01-05 11:26 UTC, dlenski commented
> Using a proxy while trying to connect to VPN is problematic, as proxies are usually behind the VPN.

While that's a _common_ use case, it's also not unheard-of that VPN users _have to go through a proxy_ to access the VPN server. (It's a dumb and inefficient setup, but I've heard of it repeatedly with different corporate VPNs.)

Perhaps you could put this behind a `--no-proxy` option or similar?

2024-01-05 11:28 UTC, dlenski requested changes

2024-01-05 11:28 UTC, dlenski commented on gp_saml_gui.py
> +        data_manager.set_network_proxy_settings(WebKit2.NetworkProxyMode.NO_PROXY, None)
I try to ensure that the network and TLS settings used for the webview are as closely matched as possible to the settings used when launching `openconnect` itself.

Could you please add `--no-proxy` to the OpenConnect command-line building (in `main`), whenever the proxy is disabled for the webview?

2024-01-08 05:35 UTC, mchehab commented on gp_saml_gui.py
> +        data_manager.set_network_proxy_settings(WebKit2.NetworkProxyMode.NO_PROXY, None)
Sure. Just pushed a new version. While here:
- I opted to pass arguments as a dict to the class, as it makes easier to add more arguments;
- I also fixed an issue if one tries to close the login window (for example, when gp_saml_gui is called with an already-validated token).

2024-03-07 21:56 UTC, dlenski commented on gp_saml_gui.py
> +            return
Could also just be…

```py
if not rs:
  return
h = rs.get_http_headers()
```

2024-03-07 21:57 UTC, dlenski commented on gp_saml_gui.py
> +    def __init__(self, html, uri, args):
Wait… you have _reversed_ the order of the `html` and `uri` arguments in the function definition, but you _haven't_ reversed them in the callsite at L360.

How can this work?

2024-03-08 06:24 UTC, mchehab commented on gp_saml_gui.py
> +    def __init__(self, html, uri, args):
heh, true. Fixed and tested:

```
writing RSA key
Looking for SAML auth tags in response to https://<vpn-url>/ssl-vpn/prelogin.esp...
Got SAML REDIRECT, opening browser...
[PAGE   ] Finished loading page https://login.microsoftonline.com/...
[PAGE   ] Finished loading page https://<vpn-url>/SAML20/SP/ACS
[SAML   ] Got SAML result headers: ...
[SAML   ] Got all required SAML headers, done.

SAML response converted to OpenConnect command line invocation:
...
SAML response converted to test-globalprotect-login.py invocation:
...
Launching OpenConnect with sudo, equivalent to:
...
Session authentication will expire at Fri Mar  8 23:17:00 2024

Using vhost-net for tun acceleration, ring size 32
```

2024-04-29 17:40 UTC, pboushy commented
@dlenski - anything pending on this? We have several people who would benefit from this being added.

We're working on some other workarounds in the meantime, but this would go a long way to resolving.

2024-04-30 06:50 UTC, mchehab commented on gp_saml_gui.py
> +        data_manager.set_network_proxy_settings(WebKit2.NetworkProxyMode.NO_PROXY, None)
Another patch with the same fix got merged:
```
c9e783116ede ("fix exception when checking about:blank response")
```
So, I dropped this patch: `a72825e87f18 ("Properly handle close window event without login")`.

2024-04-30 07:02 UTC, mchehab commented on gp_saml_gui.py
> +        data_manager.set_network_proxy_settings(WebKit2.NetworkProxyMode.NO_PROXY, None)
> Could you please add `--no-proxy` to the OpenConnect command-line building (in `main`), whenever the proxy is disabled for the webview?
Added.

2024-05-02 19:52 UTC, dlenski approved these changes

2024-05-02 19:52 UTC, merged